name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend Service
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_BACKEND_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          dir: backend/

      - name: Deploy Frontend Service
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_FRONTEND_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          dir: frontend/
          build_arg: API_URL=${{ secrets.RENDER_BACKEND_URL }}