name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend Service
        uses: render-action/deploy-web-service@v1.2.0
        with:
          service-id: ${{ secrets.RENDER_BACKEND_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          dir: backend/

      - name: Deploy Frontend Service
        uses: render-action/deploy-web-service@v1.2.0
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          dir: frontend/
          build-arg: API_URL=${{ secrets.RENDER_BACKEND_URL }}